export const exampleSyncJob = {
  job: {
    source: 'a_source',
    scope: 'a_scope',
    accountId: 'abc123',
    id: 'an_id',
    status: 'AWAITING_UPLOADS',
    done: false,
    startTimestamp: new Date(),
    numEntitiesUploaded: 0,
    numEntitiesCreated: 0,
    numEntitiesUpdated: 0,
    numEntitiesDeleted: 0,
    numEntityCreateErrors: 0,
    numEntityUpdateErrors: 0,
    numEntityDeleteErrors: 0,
    numEntityRawDataEntriesUploaded: 0,
    numEntityRawDataEntriesCreated: 0,
    numEntityRawDataEntriesUpdated: 0,
    numEntityRawDataEntriesDeleted: 0,
    numEntityRawDataEntryCreateErrors: 0,
    numEntityRawDataEntryUpdateErrors: 0,
    numEntityRawDataEntryDeleteErrors: 0,
    numRelationshipsUploaded: 0,
    numRelationshipsCreated: 0,
    numRelationshipsUpdated: 0,
    numRelationshipsDeleted: 0,
    numRelationshipCreateErrors: 0,
    numRelationshipUpdateErrors: 0,
    numRelationshipDeleteErrors: 0,
    numRelationshipRawDataEntriesUploaded: 0,
    numRelationshipRawDataEntriesCreated: 0,
    numRelationshipRawDataEntriesUpdated: 0,
    numRelationshipRawDataEntriesDeleted: 0,
    numRelationshipRawDataEntryCreateErrors: 0,
    numRelationshipRawDataEntryUpdateErrors: 0,
    numRelationshipRawDataEntryDeleteErrors: 0,
    numMappedRelationshipsCreated: 0,
    numMappedRelationshipsUpdated: 0,
    numMappedRelationshipsDeleted: 0,
    numMappedRelationshipCreateErrors: 0,
    numMappedRelationshipUpdateErrors: 0,
    numMappedRelationshipDeleteErrors: 0,
    syncMode: 'DIFF',
  },
};
